# Generated by Django 2.2 on 2019-05-06 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField(max_length=128)),
                ('nice_name', models.CharField(max_length=64)),
                ('cat_parent', models.CharField(max_length=64)),
                ('cat_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nice_name', models.CharField(max_length=64)),
                ('human_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField(max_length=128)),
                ('taxonomy', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=64)),
                ('parent', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.CharField(max_length=256)),
                ('pub_date', models.DateField()),
                ('encoded_content', models.TextField()),
                ('post_id', models.IntegerField()),
                ('post_date', models.DateTimeField()),
                ('attachment_url', models.CharField(max_length=256, null=True)),
                ('byline', models.ManyToManyField(to='main.Profile')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_tag', to='main.Tag')),
                ('post_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_tag', to='main.Tag')),
            ],
        ),
    ]
