# Generated by Django 2.2 on 2019-04-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='term_id',
            field=models.CharField(max_length=16),
        ),
    ]
