# Generated by Django 2.2 on 2019-05-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190506_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='slug',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
