# Generated by Django 2.2 on 2019-04-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190422_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='term_id',
            field=models.CharField(max_length=128),
        ),
    ]
