# Generated by Django 2.2 on 2019-05-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190506_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='parent',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
