# Generated by Django 2.2 on 2019-04-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190422_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_parent',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='nice_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='term_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='term',
            name='parent',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='term',
            name='slug',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='term',
            name='taxonomy',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_id',
            field=models.CharField(max_length=128),
        ),
    ]
